# Generated by Django 4.2.3 on 2023-07-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_driverinfo_remove_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
