# Generated by Django 4.2.3 on 2023-07-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_driverinfo_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
