# Generated by Django 4.2.3 on 2023-07-06 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_driverinfo_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='info',
        ),
        migrations.AddField(
            model_name='driverinfo',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
