# Generated by Django 4.2.3 on 2023-07-07 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_address_formated_alter_address_lat_and_more'),
        ('account', '0006_remove_customuser_info_driverinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.address'),
        ),
    ]
