# Generated by Django 4.2.3 on 2023-07-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_driverinfo_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.AddField(
            model_name='driverinfo',
            name='accepted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
