# Generated by Django 4.2.3 on 2023-07-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='req_date',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
