# Generated by Django 4.2.3 on 2023-07-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_request_req_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='formated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='long',
            field=models.FloatField(null=True),
        ),
    ]
