# Generated by Django 4.2.3 on 2023-07-07 14:20

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_address_formated_alter_address_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='req_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
