# Generated by Django 4.2.3 on 2023-07-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_request_req_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('معمولی', 'معمولی'), ('معمولی', 'فوری')], max_length=50),
        ),
    ]
